### ISSUE TITLE
--watch not working on file rename?

### ISSUE THREAD

**Issue by Rechdan** [zont/copy-and-watch#10]
I tried to rename a file and got these errors:

**Comment by zont** [comment]
Cannot reproduce.

Maybe you try to rename file in destination folder?

**Comment by Rechdan** [comment]
Maybe thats a  problem with my node version?
```
node -v
v12.18.4
```

And here is the command I used:
```
copy-and-watch --clean ./src/public/**/*.* ./dist/public
```

**Comment by NoNameProvided** [comment]
This is not restricted for file rename, simple content updates doesn't work either on Windows. I have encountered the same error, this is most likely due to different separator between MacOS and Windows. After adding a `console.log` to the `findTarget` function where the error is thrown the following can be seen: 

```
[build:copy] {
[build:copy]   target: 'build',
[build:copy]   parents: [ 'src/assets' ],
[build:copy]   parent: 'src/assets',     
[build:copy]   from: 'src/assets/styles'
[build:copy] }
[build:copy] {
[build:copy]   target: 'build',
[build:copy]   parents: [ 'src/assets' ],
[build:copy]   parent: 'src/assets',
[build:copy]   from: 'src/assets/styles/main.css'
[build:copy] }
[build:copy] [COPY] src/assets/styles/main.css to build\styles\main.css
[build:copy] [WATCH] src\assets\**\*
[build:copy] {
[build:copy]   target: 'build',
[build:copy]   parents: [ 'src/assets' ],
[build:copy]   parent: undefined,
[build:copy]   from: 'src\\assets\\styles\\main.css'
[build:copy] }
[build:copy] (node:8544) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
[build:copy]     at validateString (internal/validators.js:121:11)
[build:copy]     at Object.relative (path.js:437:5)
[build:copy]     at findTarget (C:\Users\attil\code\spreadmonitor\alteo\website\node_modules\copy-and-watch\index.js:41:33)
[build:copy]     at FSWatcher.copy (C:\Users\attil\code\spreadmonitor\alteo\website\node_modules\copy-and-watch\index.js:61:14)
[build:copy]     at FSWatcher.emit (events.js:314:20)
[build:copy]     at FSWatcher.emitWithAll (C:\Users\attil\code\spreadmonitor\alteo\website\node_modules\chokidar\index.js:524:8)
[build:copy]     at FSWatcher._emit (C:\Users\attil\code\spreadmonitor\alteo\website\node_modules\chokidar\index.js:616:8)
[build:copy]     at listener (C:\Users\attil\code\spreadmonitor\alteo\website\node_modules\chokidar\lib\nodefs-handler.js:370:20)
[build:copy] (Use `node --trace-warnings ...` to show where the warning was created)
[build:copy] (node:8544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not 
handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)[build:copy] (node:8544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.    
```

The first two print is from the startup, where the `from` parameter is not escaped, but then on update I assume the `from` parameter comes from the watcher library used, what escapes it Windows style so consequent checks will always fail.

**Comment by nicearma** [comment]
any news about this problem? i'm working in windows and the initial copy works fine but the watch shows the error and end the execution, there is any workaround ?

**Comment by NoNameProvided** [comment]
> For the workaround if I understand I have to replace the internal code of findTarget

Yes, you can use https://github.com/ds300/patch-package to apply the fix automatically while the fix doesn't land in this repo.

**Comment by ba32107** [comment]
same issue on linux

**Comment by AmitDigga** [comment]
Currently using this with other package [run-when-changed](https://www.npmjs.com/package/run-when-changed)

`npx run-when-changed --watch "FolderToWatch/**/*" --exec 'npx copy-and-watch ../FolderToWatch/**/* outputFolder/'`
