### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by alexblack** [zont/copy-and-watch#3]
Hi, I'm having trouble using `--watch`, I'm running this:

`npm run watch`

with 

`"watch": "copy-and-watch ./src/public/**/*.{html,css} ./build --watch"`

and getting this result:

> r2@1.0.0 watch /Users/alex/dev/is/r2
> copy-and-watch ./src/public/**/*.{html,css} ./build --watch

[COPY] ./src/public/panel.html to build/panel.html
[COPY] ./src/public/panel.css to build/panel.css
[WATCH] ./src/public/**/*.html
[WATCH] ./src/public/**/*.css
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1268:5)
    at findTarget (/Users/alex/dev/is/r2/node_modules/copy-and-watch/index.js:37:33)
    at FSWatcher.copy (/Users/alex/dev/is/r2/node_modules/copy-and-watch/index.js:57:14)
    at emitOne (events.js:115:13)
    at FSWatcher.emit (events.js:210:7)
    at FSWatcher.<anonymous> (/Users/alex/dev/is/r2/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/Users/alex/dev/is/r2/node_modules/chokidar/index.js:238:5)
    at FSWatcher.<anonymous> (/Users/alex/dev/is/r2/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (/Users/alex/dev/is/r2/node_modules/chokidar/lib/fsevents-handler.js:210:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! r2@1.0.0 watch: `copy-and-watch ./src/public/**/*.{html,css} ./build --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the r2@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2018-01-22T04_06_25_666Z-debug.log

**Comment by alexblack** [comment]
Ah, changing it to this resolved the issue:

`"watch": "copy-and-watch src/public/**/*.{html,css} build --watch"`

**Comment by aNickzz** [comment]
I'm also getting this error with the command `copy-and-watch src/html/* dist --watch`.
